title:            Wayne's blog
tagline:          Goose, goese, geese
description:      Yet another IT guy, and a runner
#Comment out url when working locally to resolve base urls correctly
url:              http://xuhuanze.me

# Owner/author information
owner:
  name:           Huanze Xu
  avatar:         avatar.jpg
  bio:            "Programmer, runner and writer"
  email:          xuhuanze@qq.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  # twitter:        https://twitter.com/xuhuanze
  facebook:       huanze.xu
  github:         zjxhz
  linkedin:       xuhuanze
  instagram:      
  lastfm:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:        

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Articles
    url: /articles


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Shanghai
future:      true
# pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
